### ISSUE TITLE
Always add GEDCOM file to the github Repo

### ISSUE THREAD

**Issue by zdavatz** [bcat-eu/davaz#1]
Please make sure to always add GEDCOM file to the github Repo. Gramps has an export option for that.

**Comment by bcat-eu** [comment]
I've added a gedcom file, would have to re-generate it after the tree changes but it's not a problem unless we do that very often. 

To make a PDF out of it you'd probably need another software though, there are few of those as desktop and web apps - I tried it with familyecho.com and it seems to work (I can get a PDF), there's also myheritage.com and such plus a bunch of desktop Windows and Linux programs.

@zdavatz do you have a plan for that?

**Comment by zdavatz** [comment]
Yes, I have a software, but it [only works for Mac](https://apps.apple.com/de/app/gedcom-to-dot/id1074600198). Maybe we will find something on Github. Would be nice to combine it with Github-Actions so we always have an up-to-date PDF in the Repository.

**Comment by bcat-eu** [comment]
@zdavatz we'd have to generate gedcom file from the database anyway, so another manual step is not that bad either, we wouldn't have too many changes in the tree eventually :) I'm all for using actions though, but for that it'd have to be a process that can be automated, let me know if you have an idea there. Also you may as well generate a PDF now (do we also push the PDF?)

**Comment by zdavatz** [comment]
Yes, I would always push the latest PDF version, so we can send that to all the people on the tree so they can check their data.

**Comment by zdavatz** [comment]
@bcat-eu can you push the current version of the PDF so we can have a look at it?

**Comment by bcat-eu** [comment]
@zdavatz I've got no current version, I just checked the gedcom file with a random web service to make sure a PDF can be generated from that file, this PDF was clearly wrong (I had to make some choices in the UI for it to be generated), I've deleted it right away.

Why, is there a problem with your program?

**Comment by zdavatz** [comment]
No, no problem. I was just curious which software generates the best PDF.

**Comment by bcat-eu** [comment]
@zdavatz if you want you can go here familyecho.com click import in the bottom left, choose anybody as "you" and then you can download the PDF.

**Comment by zdavatz** [comment]
@bcat-eu check this: 
![davaz](https://user-images.githubusercontent.com/4953/100897856-710d6300-34c0-11eb-9c07-75880bee2020.gif)
