### ISSUE TITLE
data of living person should stay anonymous.

### ISSUE THREAD

**Issue by zdavatz** [bcat-eu/davaz#3]
Be careful when you create the GEDCOM file, if you publish the data the living person should stay anonymous.

I think Gramps has an option for that.

**Comment by bcat-eu** [comment]
We can figure it out later when we know how we go about creating a PDF, s. https://github.com/bcat-eu/davaz/issues/1#issuecomment-736667621

At the moment it's a dumbest gedcom possible (all options are default).

**Comment by zdavatz** [comment]
Ok, perfect! Thank you!

**Comment by bcat-eu** [comment]
@zdavatz I have generated a new gedcom, expluced all living people as well as all people marked private.

You can play with the PDF generation now, I'll add info about these settings to readme..
